// @flow
export const PRODUCT_LIST_UPDATE_PRODUCTS = 'PRODUCT_LIST_UPDATE_PRODUCTS';
export const PRODUCT_LIST_UPDATE_PROPS = 'PRODUCT_LIST_UPDATE_PROPS';

export const PRODUCT_LIST_CREATE = 'PRODUCT_LIST_CREATE';
export const PRODUCT_LIST_DELETE = 'PRODUCT_LIST_DELETE';

export const PRODUCT_LIST_ADD_PERMISSION = 'PRODUCT_LIST_ADD_PERMISSION';
export const PRODUCT_LIST_REVOKE_PERMISSION = 'PRODUCT_LIST_REVOKE_PERMISSION';
