// @flow
export const WELCOME_PAGE = 'WELCOME_PAGE';
export const LOGIN_PAGE = 'LOGIN_PAGE';
export const LIST_MANAGEMENT_PAGE = 'LIST_MANAGEMENT_PAGE';
export const PRODUCT_LIST_PAGE = 'LIST_MANAGEMENT_PAGE';
export const PRODUCT_DETAILS_PAGE = 'LIST_MANAGEMENT_PAGE';